# Generated by Django 5.0.6 on 2024-07-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
