# Generated by Django 5.0.6 on 2024-07-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_program_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='users',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
