# Generated by Django 5.0.6 on 2024-07-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_event_link_alter_program_price_alter_program_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='users',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
